### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by hvbtup** [textX-tools/textX-languageserver#6]
Looks promising, but I cannot get it to work.
I started the language server

    C:\prog\Python37-32>Scripts\textxls.exe --tcp
    Server started on 127.0.0.1:5000

... and it is obviously running.

Then, in my hello.tx file, I press F1 and choose "Export Metamodel to dot".

This results in a long stack trace in the output window:

2019-01-17 18:27:53,395 UTC - ERROR - src.infrastructure.language_server - CAUGHT
Traceback (most recent call last):
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\src\infrastructure\language_server.py", line 85, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\src\infrastructure\textx_ls.py", line 182, in m_workspace__execute_command
    return self.commands[command](self, arguments)
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\src\commands\dotexport.py", line 15, in dotexport_metamodel_cmd
    metamodel_path = textx_ls.configuration.grammar_path
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\src\infrastructure\configuration.py", line 170, in grammar_path
    path = self.config_model.paths_section.grammar_path
AttributeError: 'NoneType' object has no attribute 'paths_section'
2019-01-17 18:27:53,395 UTC - ERROR - jsonrpc.manager - API Exception: {'type': 'AttributeError', 'args': ("'NoneType' object has no attribute 'paths_section'",), 'message': "'NoneType' object has no attribute 'paths_section'"}
Traceback (most recent call last):
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\third_party\jsonrpc\manager.py", line 108, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\src\infrastructure\language_server.py", line 85, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\src\infrastructure\textx_ls.py", line 182, in m_workspace__execute_command
    return self.commands[command](self, arguments)
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\src\commands\dotexport.py", line 15, in dotexport_metamodel_cmd
    metamodel_path = textx_ls.configuration.grammar_path
  File "C:\Users\hvb\.vscode\extensions\danixeee.textx-ls-1.1.0\textX-languageserver\src\infrastructure\configuration.py", line 170, in grammar_path
    path = self.config_model.paths_section.grammar_path
AttributeError: 'NoneType' object has no attribute 'paths_section'
[Error - 6:27:53 PM] Request workspace/executeCommand failed.
  Message: Server error
  Code: -32000 
[object Object]

I'm stuck.

**Comment by danixeee** [comment]
@hvbtup You can just install the extension from [marketplace](https://marketplace.visualstudio.com/items?itemName=danixeee.textx-ls) and open directory which contains you project. Language server will be started by the client, so you don't have to worry about it. 

That's obviously a bug (thanks for reporting), but since you are working on a grammar (file ending with `.tx` extension), you probably want to call `Export Model to dot` command. 

Please let me know if that solved your issue.

I am aware that there are couple of bugs here, but we started this project from scratch and we will fix them. You can take a look at [textX-LS](https://github.com/textX/textX-LS) repo, we are currently in discussion phase with some initial setup.. :)

Best,
Daniel

**Comment by hvbtup** [comment]
This helped a little bit, but ...

So there is no need to start textxls.exe --tcp script in a separate CMD window. 
Good to know; the documentation on https://github.com/textX/textX-languageserver should perhaps be updated then. It states "4. Run Server textxls --tcp" and mentions a non-exisiting fifth step.

With Export Model to dot, it kind of works, but the generated dot file (which can be seen with the viewX extension - a nice co-working of the extensions), is far too complicated:

For the hello world example ...

HelloWorldModel:
   'hello' to_greet+=Who[',']
;

Who:
   name = /[^,]*/
;
... the generated graph has 25 nodes!?

The command Export metamodel to dot still fails.

I thought "export model" was for generating a dot of a model written im my own DSL while "export metamodel" was for generating a BNF-like diagramm of my DSL's syntax.

**Comment by hvbtup** [comment]
After saving my workspace with a name (previously it was shown as unnamed workspace) and restarting VS Code, "export metamodel to dot" now works and gives the expected result.

**Comment by danixeee** [comment]
@hvbtup what you probably want is this:

1. Save your grammar to a file, e.g. `hello_world.tx`
2. In the root workspace create a `.txconfig` file like this:

```
dsl HelloWorld [ hw ] {
    paths {
	grammar: "./hello_world.tx"
    }
}
```

3. Restart VS Code (just in case)
4. Create a model and save it with `hw` extension
5. Now you can call both `Export Metamodel to dot` and `Export Model to dot`

The thing is that this extension has some built-in grammars and one of them is textx grammar. With textx grammar we are parsing other grammar files (`*.tx`).

I just tried it, here are few images:

![image](https://user-images.githubusercontent.com/16227576/51390191-e2db9e00-1b2e-11e9-9845-3a4b68b7261d.png)

![image](https://user-images.githubusercontent.com/16227576/51390359-5c738c00-1b2f-11e9-89c2-7838a0058043.png)

**Comment by hvbtup** [comment]
Yes, I forgot to mention in my previous comment that I _did_ create a .txconfig file.
